### ISSUE TITLE
Question about input format

### ISSUE THREAD

**Issue by adigitoleo** [MFraters/cpo_analyzer#19]
Hello,

I am independently working on some CPO modelling (which may eventually be superseded by ASPECT with your well-written plugin) and I'd like to try using this package for visualisation. I'm not clear on the input format, because I'm not using ASPECT. I tried to run the shearbox models from your 2021 paper, however I had trouble getting aspect to run the sample input file provided in the supplementary material:

```
----------------------------------------------------
Exception 'ExcMessage("Value \""+ write_draw_volume_weighted_lpo_list[i] +"\", set in \"Write out draw volume weighted lpo data\", is not a correct option " + "because it should contain a mineral identification and a output specifier seprated by a colon (:). This entry " + "does not follow those rules.")' on rank 0 on processing:

--------------------------------------------------------
An error occurred in line <955> of file </home/admin/srcbuilds/ASPECT-Fraters/source/postprocess/particle_lpo.cc> in function
    void aspect::Postprocess::LPO<dim>::parse_parameters(dealii::ParameterHandler&) [with int dim = 3]
The violated condition was:
    split_draw_volume_weighted_lpo_instructions.size() == 2
Additional information:
    Value "olivine Euler angles", set in "Write out draw volume weighted
    lpo data", is not a correct option because it should contain a mineral
    identification and a output specifier seprated by a colon (:). This
    entry does not follow those rules.
--------------------------------------------------------

Aborting!
----------------------------------------------------
```

I will try to fiddle with the weighted output parameter names. The relevant section of the parameter file is:

```
    subsection LPO
        set Time between data output = 1e5
        set Write in background thread = true
        set Compress lpo data files = true
        set Write out raw lpo data =
        #set Write out draw volume weighted lpo data = mineral 0: volume fraction, mineral 0: Euler angles, mineral 1: volume fraction, mineral 1: Euler angles
    end
```

So really I'm sneaking a few questions in here:
- Do you perhaps have an up-to-date parameter file for the aspect CPO plugin? I'm running from the `CPO_afterpaper_changes` branch.
- In the example folder, it seems that the input for this program is Euler angles, stored in separate .dat files for each grain. Is that correct? Maybe it would be convenient to allow input of multiple grain data from one file? Are there other ASPECT-specific things in the input that I should be aware of, or can I just turn off compression and match the .dat format? I will try a few things, unfortunately I'm not familiar with Rust but maybe I can help a little bit.

Thanks for making your code and methods public and accessible, it has already helped me a lot.

**Comment by MFraters** [comment]
Hello @adigitoleo,

Thanks for your interest in the this and the aspect lpo code. 

>  I had trouble getting aspect to run the sample input file provided in the supplementary material

Ah, I see what the problem is here. the `#` comments out the line, which fills in a default value of `olivine Euler angles,enstatite Euler angles`, which is not correct. Just removing the `#` will provide you with the correct values.

> Do you perhaps have an up-to-date parameter file for the aspect CPO plugin? I'm running from the CPO_afterpaper_changes branch.

Sure, I don't think much has changed, but here is a recent version which I used with this branch:

```
set Dimension   = 3
set End time    = 30e6
set Use years in output instead of seconds = true
set Timing output frequency = 50
set Maximum time step = 5000

set Output directory = iofiles/cornerflow/reference/ ## Annotation: Output directory  

subsection Geometry model
  set Model name = box
  subsection Box
    set Box origin Y coordinate = 0
    set Box origin X coordinate = 0
    set Box origin Z coordinate = 0
    set Z extent = 300e3
    set X extent = 300e3
    set Y extent = 25e3 #6250
    set Z repetitions = 24 #16 #16
    set X repetitions = 24 #48 #128
    set Y repetitions = 2
  end
end

subsection Initial temperature model
  set Model name = function
end

#subsection Boundary velocity model
#  set Zero velocity boundary indicators = top
#end

subsection Gravity model
  set Model name = vertical
  subsection Vertical
    set Magnitude = 0
  end
end

subsection Material model
  set Model name = simple 
  subsection Simple model
    set Viscosity = 5e22 ## Annotation: visocosity
  end
end

subsection Mesh refinement
  set Initial global refinement = 0
  set Initial adaptive refinement = 0
  set Minimum refinement level = 0
end

subsection Compositional fields
  set Number of fields = 1
  set Names of fields = water
 set Compositional field methods = static
end

subsection Initial composition model
  set Model name = function

  subsection Function
    set Variable names      = x,y,z
    set Function expression = if(z<-0.5*x+300000, 800, 25) ## Annotation: water function expression
  end
end

subsection Postprocess
  set List of postprocessors = visualization, particles, lpo

  subsection Visualization
    set Output format                 = vtu
    set Time between graphical output = 50000
    set List of output variables = strain rate, viscosity
  end

  subsection Particles
    set Number of particles = 750
    set Time between data output = 25000
    set List of particle properties = lpo, lpo bingham average,lpo elastic tensor, decompose elastic matrix, integrated strain invariant
    set Exclude output properties = a_cosine_matrix, volume fraction
    set Integration scheme = rk4

    subsection LPO
      set Random number seed = 200
      set Number of grains per praticle = 500 ## Annotation: grain count
      set Property advection method = Backward Euler #Crank-Nicolson #Backward Euler ## Annotation: Property advection method
      set Property advection tolerance = 1e-15
       subsection D-Rex 2004
         set Minerals = Olivine: Karato 2008, Enstatite ## Annotation: Minerals
         set Mobility = 125 ## Annotation: LPO Mobility
         set Volume fractions minerals = 0.7, 0.3 ## Annotation: Volume fractions minerals
         set Stress exponents = 3.5
         set Exponents p = 1.5
         set Nucleation efficientcy = 5 ## Annotation: Nucleation efficientcy
         set Threshold GBS = 0.3 ## Annotation: TGBS
       end
    end
    subsection LpoBinghamAverage
      set Random number seed = 200
    end
  end
  subsection LPO
    set Time between data output = 100000
    set Write in background thread = true
    set Compress lpo data files = true #false
      set Write out raw lpo data = 
      set Write out draw volume weighted lpo data = mineral 0: volume fraction, mineral 0: Euler angles, mineral 1: volume fraction, mineral 1: Euler angles
  end
end

subsection Boundary velocity model
  set Prescribed velocity boundary indicators =  top: function
  set Tangential velocity boundary indicators = left, front, back 
    subsection Function
    set Variable names      = x,y,z
    set Function constants  = cm=0.01, year=1
    set Function expression = 1.0*cm/year;0.0;0.0
  end
end
```

> n the example folder, it seems that the input for this program is Euler angles, stored in separate .dat files for each grain. Is that correct? Maybe it would be convenient to allow input of multiple grain data from one file? Are there other ASPECT-specific things in the input that I should be aware of, or can I just turn off compression and match the .dat format? I will try a few things, unfortunately I'm not familiar with Rust but maybe I can help a little bit.

I think you should be able to put all the particle information in one file and all the grain information in one file. ASPECT builds the files based on MPI-process, so it will contain many particles per file, and many grains per file. As long as the id for the grain links to the correct particle, it should work. Let me know if this is what you meant, and if it works for  you. 

A lot of the columns in the particle*.dat file are optional, so you can remove them (and turn those parts off in the configuration), see https://docs.rs/cpo_analyzer/latest/cpo_analyzer/configuration/particle_record/struct.ParticleRecord.html. If you are filling in those entries by hand, you will definitely want to turn off compression. 

> Thanks for making your code and methods public and accessible, it has already helped me a lot.

That is great to hear! Let me know if you have any further questions :)

**Comment by adigitoleo** [comment]
Thanks for the information and example config. I have been able to run the simulation.
